# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB, InfluxDB-writer and Grafana services
# for the Mainflux platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

volumes:
  mainflux-exporter-volume:

services:
  mainflux-exporter:
    image: mainflux/exporter:latest
    container_name: mainflux-exporter
    restart: on-failure
    environment:
      MF_NATS_URL: ${MF_NATS_URL}
      MF_EXPORTER_CONF_PATH: ${MF_EXPORTER_CONF_PATH}
      MF_EXPORTER_MQTT_HOST: ${MF_EXPORTER_MQTT_HOST}
      MF_EXPORTER_MQTT_USERNAME: ${MF_EXPORTER_MQTT_USERNAME}
      MF_EXPORTER_MQTT_PASSWORD: ${MF_EXPORTER_MQTT_PASSWORD}
      MF_EXPORTER_MQTT_CHANNEL: ${MF_EXPORTER_MQTT_CHANNEL}
      MF_EXPORTER_MQTT_SKIP_TLS: ${MF_EXPORTER_MQTT_SKIP_TLS}
      MF_EXPORTER_MQTT_MTLS: ${MF_EXPORTER_MQTT_MTLS}
      MF_EXPORTER_MQTT_CA: ${MF_EXPORTER_MQTT_CA}
      MF_EXPORTER_MQTT_CLIENT_CERT: ${MF_EXPORTER_MQTT_CLIENT_CERT}
      MF_EXPORTER_MQTT_CLIENT_PK: ${MF_EXPORTER_MQTT_CLIENT_PK}
      MF_EXPORTER_CHANNELS_CONFIG: ${MF_EXPORTER_CHANNELS_CONFIG}
    ports:
      - ${MF_EXPORTER_PORT}:${MF_EXPORTER_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - ./channels.toml:/config/channels.toml
      - ./config.toml:/config/config.toml

