
[exp]
  log_level = "debug"
  nats = "nats://127.0.0.1:4222"
  port = "8170"

[mqtt]
  ca_path = "ca.crt"
  cert_path = "thing.crt"
  password = "53a795db-e46c-4d75-8ddc-6d2975337a4f"
  username = "e2032af3-7323-47d6-8e8d-abe9eb0a0a8f"
  channel = "ace5c9ef-54cf-4d8e-8b4c-2f1908ff2cda"
  host = "tcp://142.93.118.47:18831"
  mtls = false
  priv_key_path = "thing.key"
  qos = 0
  retain = false
  skip_tls_ver = false

[[routes]]
  mqtt_topic = "4c66a785-1900-4844-8caa-56fb8cfd61eb"
  nats_topic = "*"
  type = "mflx"

[[routes]]
  mqtt_topic = "4c66a785-1900-4844-8caa-56fb8cfd61eb"
  nats_topic = "*"
  type = "plain"
