
[exp]
  log_level = "debug"
  nats = "nats://127.0.0.1:4222"
  port = "8170"

[mqtt]
  ca_path = "ca.crt"
  cert_path = "thing.crt"
  password = "b7e6e968-ff42-413e-a360-9118c8bb90f0"
  username = "8cd9817e-55be-4e7b-8d6b-46897e9facc1"
  channel = "cfb02ccf-6703-4603-a042-2271532801f4"
  host = "tcp://localhost:18831"
  mtls = false
  priv_key_path = "thing.key"
  qos = 0
  retain = false
  skip_tls_ver = false

[[routes]]
  mqtt_topic = "channels/cfb02ccf-6703-4603-a042-2271532801f4/messages"
  nats_topic = "*"
  type = "mfx"

[[routes]]
  mqtt_topic = "4c66a785-1900-4844-8caa-56fb8cfd61eb"
  nats_topic = "*"
  type = "plain"
